apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# When you run or deploy this, Kustomize will automatically look for 
# the kustomization.yaml file inside these folders and apply its resources.
resources:
  - rules
  - servicemonitors

#  Ensures everything is deployed into your monitoring stack.
namespace: monitoring