apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack-root
  namespace: argocd

  labels:
    stack: observability
    component: orchestrator
    app.kubernetes.io/component: root-app
    app.kubernetes.io/part-of: monitoring-stack
    scope: cross-environment
    managed-by: argocd

spec:
  # Links to the project inside the same folder
  project: observability-project
  source:
    repoURL: https://github.com/SodiqIshola/DevOps-Project
    targetRevision: main
    path: "placeholder"       # Terraform will overwrite this
    directory:
      recurse: true # Scans the folder for all Application manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  info:
    - name: 'Pattern'
      value: 'App-of-Apps (Root): Centralized management for the entire observability suite.'
    - name: 'Discovery'
      value: 'Recursively syncs Metrics, Logging, Tracing, and Collector applications.'
    - name: 'Operation'
      value: 'Provides a unified tree view and single point of control for the monitoring stack.'
