apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Deploys all resources into this specific namespace for environment isolation
namespace: dev-namespace

# Transforms metadata.name of all resources by adding a '-dev' suffix to ensure unique naming within the cluster.
nameSuffix: -dev

# Injects environment tags for isolation and filtering.
labels:
  - pairs:
      environment: development
    includeSelectors: false # false keeps existing Base selectors intact to prevent Pod mismatch.
    includeTemplates: true  # true ensures Pods carry labels for log/metric aggregation.

# Environment-specific overrides for the development 
patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - path: ingress-patch.yaml 
  - path: service-patch.yaml 
  - path: servicemonitor-patch.yaml
    # Explicitly matches the ServiceMonitor by kind and name for precise patching
    target:
      kind: ServiceMonitor
      name: node-app-monitor




