# Patch to update ServiceMonitor for the dev environment
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-monitor
spec:
  namespaceSelector:
    matchNames:
      - dev-namespace  # Update to match your overlay namespace
