extensions:
  health_check:
    endpoint: 0.0.0.0:13133

# This is how the OpenTelemetry Collector accepts data from your applications.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  
      http:
        endpoint: 0.0.0.0:4318

exporters:  
  debug:
    verbosity: detailed

  otlp/jaeger:
    endpoint: "jaeger:4317" 
    tls:
      insecure: true
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

processors:
  batch:
    send_batch_size: 1000
    timeout: 1s

service:
  extensions: [health_check] 

  telemetry:
    metrics:
      address: "0.0.0.0:8888" # Collector's own performance metrics
      
  pipelines:
    traces:
      receivers: [otlp]  
      processors: [batch] 
      exporters: [otlp/jaeger, otlp/tempo]




