apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-apps-project
  namespace: argocd
spec:
  description: "RBAC boundary for production workloads"
  
  # Restricts deployments to the production namespace
  destinations:
    - namespace: prod-namespace
      server: https://kubernetes.default.svc
  
  # Approved source repositories
  sourceRepos:
    - "https://github.com/SodiqIshola/DevOps-Project"

  # Allows standard namespaced Kubernetes resources
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Disallows cluster-scoped resource management
  clusterResourceWhitelist:
    - group: ''
      kind: 'none'