
# -- PROMTAIL CONFIGURATION --
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# CLIENTS: Defines where to send the gathered logs (Our Loki container)
clients:
  - url: http://loki:3100/loki/api/v1/push

# SCRAPE_CONFIGS: Defines WHICH files to watch and HOW to label them
scrape_configs:
  - job_name: node_app_files
    static_configs:
      - targets:
          - localhost
        labels:
          job: node-task-app
          host: node-app 
          __path__: /var/log/node-app/*.log


    # PIPELINE_STAGES: Tailored for your Winston JSON format
    pipeline_stages:
      - json:
          expressions:
            log_time: timestamp
            log_level: level
            log_service: service

      # Use the extracted 'log_time' as the official event time
      - timestamp:
          source: log_time
          format: RFC3339
          location: "America/Toronto"

      # Promote the JSON 'level' and 'service' fields to searchable labels in Loki
      - labels:
          level: log_level
          service: log_service

      # Clean up the output in Grafana by making the main message the 'content'
      - output:
          source: message

