apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-app-appset
  namespace: argocd

spec:
  goTemplate: true

  generators:

    # DEV (auto sync)
    - git:
        repoURL: https://github.com/SodiqIshola/DevOps-Project
        revision: main
        directories:
          - path: k8s/apps/nodejs-app/platform/aws/dev

    # PROD (manual)
    - git:
        repoURL: https://github.com/SodiqIshola/DevOps-Project
        revision: main
        directories:
          - path: k8s/apps/nodejs-app/platform/aws/prod

  template:
    metadata:
      name: nodejs-app-{{.path.basename}}
      labels:
        env: "{{.path.basename}}"

    spec:
      project: "{{.path.basename}}-apps-project"

      source:
        repoURL: https://github.com/SodiqIshola/DevOps-Project
        targetRevision: main
        path: "{{.path.path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}-namespace"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true

  templatePatch: |
    {{- if eq .path.basename "dev" }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    {{- end }}

  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m




