# -----------------------------------------------------------------------------
# PERSISTENT VOLUME CLAIM (PVC)
# Purpose: Requests a specific amount of durable storage from the cluster.
#
# Since no specific PV (PersistentVolume) or StorageClass is defined here, 
# Kubernetes uses "Dynamic Provisioning." It automatically pulls the 
# requested 1Gi from the cluster's default storage pool, acting like a 
# "vending machine" for disk space so you don't have to set up hardware manually.
# -----------------------------------------------------------------------------
apiVersion: v1                      # Specifies the API version for the PVC resource
kind: PersistentVolumeClaim         # Defines this object as a request for storage
metadata:
  name: node-app-log-pvc            # The unique ID used to link this storage to your app
  namespace: app                     # Moves this storage request into the 'app' folder
spec:
  accessModes:
    - ReadWriteOnce                 # Sets the permission: only one "node" can write at a time
  storageClassName: local-path      # This tells k3d to auto-create the PV for you
  resources:
    requests:
      storage: 1Gi                  # The specific amount of space (1 Gigabyte) being asked for
