apiVersion: v1                      # Standard API version for core resources
kind: Namespace                     # Defines this as a "Cluster Folder"
metadata:
  name: prod-namespace                        # The unique name for your application environment
