apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-monitoring-root
  namespace: argocd
spec:
  project: dev-apps-project

  source:
    repoURL: https://github.com/SodiqIshola/DevOps-Project
    targetRevision: HEAD
    path: k8s/apps/nodejs-app/argo-cd/development  # Bootstrap folder for dev environment
    directory:
      recurse: true       # Recursively deploy all manifests in the directory

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true        # Clean up obsolete resources
      selfHeal: true     # Reconcile drift automatically