apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.6/manifests/install.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
