
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rules-servicemonitor-assets
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

  
  labels:
    stack: observability
    component: monitoring-definitions
    app.kubernetes.io/component: observability-logic 
    app.kubernetes.io/part-of: monitoring-stack
    scope: cross-environment
    managed-by: argocd

  
spec:
  project: observability-project
  source:
    repoURL: https://github.com/SodiqIshola/DevOps-Project
    targetRevision: main
    # Path to the folder containing the kustomization.yaml above
    path: k8s/monitoring 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  info:
    - name: 'Description'
      value: 'Custom PrometheusRules and ServiceMonitors for metrics discovery.'
    - name: 'Implementation'
      value: 'Kustomize-driven application of custom observability manifests.'
    - name: 'Scope'
      value: 'Purely manifest-based definitions; no active services or collectors.'


