
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "2"

  labels:
    stack: observability
    component: tracing
    app.kubernetes.io/component: backend-engine
    app.kubernetes.io/part-of: monitoring-stack
    scope: cross-environment
    managed-by: argocd

spec:
  project: observability-project

  # Multiple sources allow combining the official Helm chart with local Git values
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: tempo
      targetRevision: 2.0.0
      helm:
        valueFiles:
          # $values refers to the 'ref: values' defined in the second source below
          - $values/k8s/monitoring/helm/values/tempo.yaml

    - repoURL: https://github.com/SodiqIshola/DevOps-Project
      targetRevision: main
      ref: values 

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring # Deployment target namespace
  syncPolicy:
    automated:
      prune: true      # Automatically deletes resources removed from Git
      selfHeal: true   # Reverts manual 'kubectl' changes to match Git state
    syncOptions:
      - CreateNamespace=true # Ensures 'monitoring' exists before deployment
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m 

  info:
    - name: 'Description'
      value: 'High-scale distributed tracing backend for environment-wide observability.'
    - name: 'Configuration'
      value: 'Hybrid Helm deployment using customized local storage and retention policies.'
    - name: 'Sequence'
      value: 'Sync Wave 2: Prepared as a target for Alloy and application spans.'
