# my global config: This section sets the general settings for prometheus 
global:

  # Prometheus will collect metrics every 15 seconds from each target
  scrape_interval: 15s 
  # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s 


# A scrape configuration tell prometheus what applications to monitor
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      # target are the apps prometheus will collect metrics from itself. internal metrics 
      - targets: ["prometheus:9090"]
        labels:
          app: "prometheus"

  # Scrape your Node.js Task App
  - job_name: "node-app"
    static_configs:
      # target are the apps prometheus will collect metrics 
      - targets: ["node-app:3000"]
        labels:
          app: "node-app"

  # Scrape Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      # target are the apps prometheus will collect metrics 
      - targets: ["node-exporter:9100"]
        labels:
          app: "node-exporter"

