# loki-aws.yaml
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
    storageClass: gp3

gateway:
  enabled: true
  # --- INGRESS PATCHED FOR AWS ALB ---
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: "alb"

      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: platform
      alb.ingress.kubernetes.io/wafv2-acl-arn: "${waf_arn}"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=600"

    hosts:
      - host: "" 
        paths:
          - path: /loki
            pathType: Prefix
          - path: /loki/*
            pathType: Prefix
    

  # --- HEALTH CHECKS ---
  startupProbe:
    httpGet:
      path: /
      port: http-metrics
    failureThreshold: 15
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: http-metrics
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /
      port: http-metrics
    periodSeconds: 10
