# prometheus-stack-aws.yaml
prometheus:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: "alb"

      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: platform
      alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ca-central-1:649999313359:regional/webacl/my-eks-cluster-waf-waf/6f58b0ad-ddbc-4f25-be99-77aab4f978d6"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

      # --- AWS ALB HEALTH CHECK ---
      # Matches the routePrefix and Prometheus internal port (9090)
      alb.ingress.kubernetes.io/healthcheck-port: '9090'
      alb.ingress.kubernetes.io/healthcheck-path: /prometheus/-/ready
      alb.ingress.kubernetes.io/success-codes: '200'

    hosts:
      - "" 
    path: /prometheus
    pathType: Prefix

  prometheusSpec:
    externalUrl: "/prometheus"
    routePrefix: /prometheus

    containers:
      - name: prometheus
        startupProbe:
          httpGet:
            path: /prometheus/-/ready
            port: http-web
          failureThreshold: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /prometheus/-/healthy
            port: http-web
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /prometheus/-/ready
            port: http-web
          periodSeconds: 10
          failureThreshold: 3

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  persistence:
    enabled: true
    storageClassName: gp3
    type: pvc
    size: 2Gi
  
  initChownData:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: "alb"

      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: platform
      alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ca-central-1:649999313359:regional/webacl/my-eks-cluster-waf-waf/6f58b0ad-ddbc-4f25-be99-77aab4f978d6"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

      # --- AWS ALB HEALTH CHECK ---
      # Grafana internal port is 3000
      alb.ingress.kubernetes.io/healthcheck-port: '3000'
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/success-codes: '200'

    hosts:
      - ""
    path: /grafana
    pathType: Prefix
    extraPaths: []

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true

